### ISSUE TITLE
Method to create sequence

### ISSUE THREAD

**Issue by sooners87** [robmorgan/phinx#176]
DB: postgres

To create a sequence i am executing like this

$this->execute("CREATE SEQUENCE test_seq
                        START WITH 1
                        INCREMENT BY 1
                        NO MINVALUE
                        NO MAXVALUE
                        CACHE 1;");

Is there a method to create sequence?

**Comment by robmorgan** [comment]
No not at the moment, I'll add one if I see further support from the community.

**Comment by celorodovalho** [comment]
:+1: for this feature

**Comment by djcvijic** [comment]
Also 👍

**Comment by lorenzo** [comment]
pull requests appreciated :)

**Comment by djcvijic** [comment]
@lorenzo I'd like some feedback please on the way I would implement this before I start.

I would implement createSequence, getSequence, hasSequence and dropSequence on the AdapterInterface (or maybe DirectActionInterface?), and also same-named methods directly on the MigrationInterface - since sequences are separate from tables and all these methods would be called independently from the context of any table.

Also, please note that these methods would only be implemented for Postgres and SqlServer, since MySql and Sqlite do not have sequences in the same sense, as far as I know. Please correct me if something has changed.

Please check out my first commit for the exact way these methods are called, I've made a commit in my fork, where I've written only the unit tests as I imagine them:
https://github.com/djcvijic/phinx/commit/815d012fba51f83783ab11fa25fe9bb040ee9274

**Comment by djcvijic** [comment]
@lorenzo Ping! In case you missed this message while there were outages on Github.

By the way thank you for collaborator status :)

**Comment by lorenzo** [comment]
@djcvijic Sorry I missed this, I was out travelling. 

Add the methods to `AdapterInterface`, I'm not sure yet if it is a great idea to add them to MigrationInterface.  Your test code looks alright!

**Comment by djcvijic** [comment]
Ok! I could just not add them to the MigrationInterface, that would be even easier for me. In that case, instead of
`$this->createSequence('sequence1');` the usage within migrations would look like
`$this->getAdapter()->createSequence('sequence1')`. It's just a bit longer but that seems ok to me.
