### ISSUE TITLE
Add command line options for PHINX_DBNAME etc (for TextWrapper)

### ISSUE THREAD

**Issue by adamski** [robmorgan/phinx#460]
I want to add PHINX_DBNAME, PHINX_DBUSER, PHINX_DBPASS options from the config file. 
They're currently being set by environment variables, but now with the TextWrapper class I need them to be set from within the code, so I can do something like:
```php
$wrap = new Phinx\Wrapper\TextWrapper(
    $app, 
    array(
        'configuration' => BASEPATH.'../phinx.yml', 
        'parser' => 'yaml', 
        'name' => 'myDbName', 
        'user' => 'myDbUser', 
        'pass' => 'password')
    );
```
And have the extra config settings override those in phinx.yml
I'm happy to try and do this as I need it for the project I'm currently working on. Any pointers would be appreciated.

**Comment by shadowhand** [comment]
That's not what we want to achieve with TextWrapper. The goal is not to alter any of Phinx's underlying code with regard to how configuration is loaded, but simply to allow Phinx to be called from other code.

That said, there is a larger goal (for 0.5.0 or 1.0) to refactor Phinx so that the core is callable from code, and the console part is appended... basically flipping the current system inside out.

**Comment by adamski** [comment]
OK I realised I was doing it wrong - I was setting the environment variables with putenv to simulate how I would do it on the command line. After reading a post on https://github.com/robmorgan/phinx/issues/137 I see the correct way is to set it via e.g. ```$_SERVER['PHINX_DBNAME'] = 'myDbName'```

Please add this to the docs !!
