### ISSUE TITLE
Rollback question, in conjunction with the new -d option.

### ISSUE THREAD

**Issue by rquadling** [robmorgan/phinx#628]
Hi.

Not sure how much of an issue this really is, but I think it is something that could be addressed relatively easily.

The scenario is where you have multiple developers creating features with migrations in each feature. All code in development is passing tests.

Features are finished and merged into develop (we are using git-flow, but whatever really).

Tests still pass.

Release made and the code is deployed to the staging/testing server. Migrations from the finished features are run. Tests run. Still all passing.

Release is finished, merged to master and deployed.

Migrations run (and for the sake of this example, this took place at 10:00PM local time).

Tests fail!!!!!

At this point, we don't know what migration to roll back to. But we DO know that we want to roll back to the last migration that was executed before the 10:00PM migration run.

Currently, the only way to get to that migration is to open up the phinxlog table and examine it.

The new `-d|--date=DATE` option would look to be the one that covers this, but in fact the "date" is actually the closest migration CREATION date, not EXECUTION date.

I'm in the process of producing a breakpoint option, in which the full phinx log is exposed - `getVersions()` behaves as normal and `getFullVersions()` returns the full phinxlog rows.

I think getting the breakpoint operational and / or revising the date to be the execution date (which requires access to the full row and not just version number from the phinxlog) would be a suitable option.

And/or/maybe, introduce a sort of "which date" option (creation / execution / completion) - but not sure how that would all fit together easily.

Regards,

Richard.

**Comment by rquadling** [comment]
Also, if multiple features with multiple migrations are released in one hit, any target could well have been mixed in with other branches migrations. This gets harder when some branches have been open a while. Normally the migrations are created early in the branches life.

The mixing up of the sequence of migrations means that you cannot rollback to a target if the intent is to rollback the migrations that you just ran.

If this doesn't make sense, here is a made up example using 3 developers.

Dev1 - Branch A - Migration created 20150101
Dev2 - Branch B - Migration created 20150202
Dev3 - Branch C - Migration created 20150303

Dev2 and Dev3 finish there features and so, master and production get migrations 20150202 and 20150303.

These are deployed live on 2015-04-04 04:04:04 (for example).

Now Dev1 finishes there branch.

Released to master.

Prior to migration, the status would look like ...

```
down 20150101
  up 20150202
  up 20150303
```

So, migrations are performed, (20150101 is now up), tests ran and fail.

Cannot rollback using ```-t|--target``` or ```-d|--date```.

Even my breakpoint feature won't help.

What is required is to be able to rollback the migrations that were executed before 2015-04-04 04:04:04.

I hope that makes some more sense.

**Comment by daniel-gomes-sociomantic** [comment]
we're currently starting to test phinx for our migration needs and in local testing ran into precisely the same issue (as we often have the same situation of migrations being written by different developers in different branches at the same time).

I wrote a little script which rollbacks the "local branches migrations" before checking out another branch (or rebasing, for that matter), but the problem is indeed determining what are the "local branches migrations". The script git diffs the migrations folder between the current commit and the merge-base of the local branch with the branch to checkout, but since phinx offers no way (that I know of) to rollback individuals migrations, it rollbacks (with no arguments) as many times as there are migrations on the diff. 

The problem is if @rquadling's situation happens (because of rebases, which we also do after production deploys), then after the step at:

> So, migrations are performed, (20150101 is now up), tests ran and fail.

we can't change branches anymore, as a rollback (again, without arguments) would not rollback the "local branch migration" (`20150101`) but the "last" migration (`20150303`).

> What is required is to be able to rollback the migrations that were executed before 2015-04-04 04:04:04.

We would need something similar: with my approach (which seems good to me but I don't guarantee it's the best) I would like to be able to rollback all migrations done *after* the merge-base (ie. where the current branch branched off of the other branch).

Either that or allow to rollback individual migrations :-)

**Comment by rquadling** [comment]
One of the issues with phinx at the moment is that the rollback target is, in essence, migration creation date and not migration execution date.

Now that ``phinx status -v`` shows the execution datetime, one mechanism COULD be to use something like (as yet undeveloped) ``phinx rollback --execution <date>`` and rather than comparing version numbers for the target, it compared the execution date.

For @daniel-gomes-sociomantic issue, if a breakpoint is set when the initial branch is created or switched, the rollback would be ``phinx rollback -t 0``. But again, execution date rollback is far superior to migration creation rollback.

Anyway, this is something I'll be working on as we have a team of devs here and we are ALL complaining about this.

OOI. We also have a script that moves migration datetime/filenames/etc. so we can move migrations that have been created a while ago in a feature branch and push them to now (ish). Again, not a perfect solution, but it does mean that by the time you get to deploy them, they look they were created recently. The rename is handled by git so you don't lose history.

It compares the phinxlogs between your local and production DBs (assuming you've got read access to the production server). Happy to talk through the code if anyone is interested.

**Comment by daniel-gomes-sociomantic** [comment]
So I've been playing with this some more and I think this problem reveals something fundamentally wrong (or at least to me, totally unexpected) about with the inner-working of phinx...

To reproduce:
* Create empty directory and cd into it.
* Install phinx (`php composer.phar require robmorgan/phinx`, `php composer.phar init` and configure your local database in `phinx.yml`).
* Create a migration, eg. `vendor/bin/phinx create FirstMigration`:

```
== 20151117182005 FirstMigration: migrating
== 20151117182005 FirstMigration: migrated 0.0707s
```

* Migrate with `vendor/bin/phinx migrate`. 
* Let's check the status:

```
Status  Migration ID    Migration Name 
-----------------------------------------
    up  20151117182005  FirstMigration
```

* Now, let's simulate the situation described in this issue, when because of a rebase you end up having a down migration with a version number before your branch's migration. For this, we do:
  * `cp migrations/20151117182005_first_migration.php migrations/20151116122005_some_other_migration.php`
  * Edit `migrations/20151116122005_some_other_migration.php` and change the class name to `SomeOtherMigration` (don't bother with the content).

* The status now mentions the new migration as being down, as expected:

```
 Status  Migration ID    Migration Name 
-----------------------------------------
   down  20151116122005  SomeOtherMigration
     up  20151117182005  FirstMigration
```

* so let's migrate! `vendor/bin/phinx migrate`:

```
 == 20151116122005 SomeOtherMigration: migrating
 == 20151116122005 SomeOtherMigration: migrated 0.0623s
```

* so far so good, as the status shows:

```
Status  Migration ID    Migration Name 
-----------------------------------------
     up  20151116122005  SomeOtherMigration
     up  20151117182005  FirstMigration
```

* Ups, turns out we need to do something else before migrating, so let's `vendor/bin/phinx rollback` (no arguments) to get rid of `SomeOtherMigration`:

```
 == 20151117182005 FirstMigration: reverting
 == 20151117182005 FirstMigration: reverted 0.0745s
```

And here's what to me is completely unexpected: `FirstMigration` got rollbacked! In other words, even though I just up'ed a certain migration (`SomeOtherMigration`), when rolling back the last migrating immediately after, some other migration is rolled back!

**Comment by rquadling** [comment]
That's what happens. It is wrong. See ``phinx status -v`` to see the execution times.

**Comment by rquadling** [comment]
My initial comment is ancient ( at least in developers time ). Since then, I've come to understand the issue and am waiting for some time to create a PR to fix it.

**Comment by daniel-gomes-sociomantic** [comment]
by fixing it you mean sorting the up-migrations by execution time instead of version name when handling rollbacks, so that (for my case, for instance) the last one is the last executed one as opposed to the one with the "last" version name?

**Comment by rquadling** [comment]
That's it. The version name really should only be used to see what needs to be migrated.

**Comment by daniel-gomes-sociomantic** [comment]
agreed. I might find the time soon to have a look, will let you know

**Comment by voidcontext** [comment]
@robmorgan What are your thoughts on this? Is there any chance to have this feature in a future release?

**Comment by voidcontext** [comment]
I wonder why this issue and the related PR is ignored by the repo owner...

**Comment by daniel-gomes-sociomantic** [comment]
@rquadling think it's fine to close this now :-)

**Comment by rquadling** [comment]
Oh yes!
