### ISSUE TITLE
.gitignore Db class issue

### ISSUE THREAD

**Issue by fissben** [robmorgan/phinx#965]
Hello, there.

I found an issue with .gitignore file. 
while ` ignorecase = true` option is set, `vendor/robmorgan/phinx/src/Phinx/Db` folder is ignored by git and didn't push to remote server(prod or test)

Imho, good solution is to change default folder for phinx migrations/seeds (db/(migration|seeds) for now) to some other folder or delete this from .gitignore

**Comment by thorne51** [comment]
Hmm... seems this is due to the package's .gitignore containing the following lines:

```
# ignore core development artifacts
db
migrations
```

I'll submit a pull request shortly to change those to use relative paths as `./db` which seems to resolve the issue.

As an aside, not sure if this is standard or not, but afaik normally the vendor folder is ignored entirely in order to keep your project's repository slim, and upon deployment you'd run a `composer install` after pulling changes on your test/prod environment. You might have your own reasons for including it though...

**Comment by thorne51** [comment]
@fissben See 89f4fa27b302a6234b9676fa2bce2af83198e1bd

**Comment by shadowhand** [comment]
Are you adding `vendor/` to your source control? I don't see how this issue could happen with normal composer/git config.

**Comment by thorne51** [comment]
> Are you adding vendor/ to your source control? I don't see how this issue could happen with normal composer/git config.

It does seem like he is adding it to his source control. I've managed to reproduce the issue with a blank composer install and tested with different copies of the .gitignore as reversed here #971

**Comment by fissben** [comment]
Yeah guys, you are right, vendor folder was added to git. This is project requirements. For now, I just delete this line from .gitignore and this helps. I was create this topic for users, who tries to use your lib  just like me.  So for now, i'll close issue.

thnx

**Comment by thorne51** [comment]
Ok, just remember to redo the change whenever you update your composer libraries.

**Comment by thorne51** [comment]
@fissben My pull request has been merged. If you get the updated version the problem should be resolved.
